name: Package and release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Generate changelog
        run: |
          apt update && apt install -y luarocks
          ./utils/changelog > CHANGELOG.md

      - name: Package and release
        uses: BigWigsMods/packager@064e524
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
