name: Package and release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          # this fetches everything, we'll need it to generate changelogs
          fetch-depth: 0

      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1

      - name: Generate changelog
        run: |
          lua utils/changelog > CHANGELOG.md

      - name: Package and release
        uses: BigWigsMods/packager@064e524
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
