name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Generate changelog
        run: |
          sudo apt-get -q update
          sudo apt-get -qy install lua5.1 luarocks
          lua utils/changelog > CHANGELOG.md

      - name: Dump
        run: |
          ls -la CHANGELOG.md
          cat CHANGELOG.md
          git tag
