name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Generate changelog
        run: |
          sudo apt update && sudo apt install -y luarocks
          lua /utils/changelog > CHANGELOG.md
          pwd

      - name: Dump
        run: |
          ls -la CHANGELOG.md
          cat CHANGELOG.md
