name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need to get all the history and refs

      - name: Generate changelog
        run: |
          sudo apt-get -q update
          sudo apt-get -qy install lua5.1 luarocks
          lua utils/changelog > CHANGELOG.md

      - name: Dump
        run: |
          cat CHANGELOG.md
          git log -3
          git tag
          ls -la
